version: "3.9"

services:
  backend:
    container_name: "main-api"
    build: .
    working_dir: /app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.__main__:app --host 0.0.0.0 --reload'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: "postgres_db"
#    env_file:
#      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    restart: always

#  redis:
#    image: redis
# kafka ?

volumes:
  postgres_data: