version: "3.9"

services:
  backend:
    container_name: "main-api"
    build: .
    command: uvicorn app.__main__:app --host 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - DEBUG='true'
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: "postgres_db"
    restart: always
#    env_file:
#      - ./.env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: